name: Moirae Creatives Grid
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34495b'
    - '#e7eae9'
    - '#8c8a85'
    - '#c5a293'
    - '#54717c'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
