name: Moirae Creatives Grid
favicon: null
layout_spectrum: 0.41597
typography_spectrum: 0.27068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2d38'
    - '#e6e9e8'
    - '#908f8a'
    - '#875946'
    - '#d1a791'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.30474320286884904
  rhythmicContrast: 0.25
purpose: []
